"""empty message

Revision ID: 8dcf771bdb4c
Revises: 
Create Date: 2024-12-12 16:01:08.589918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcf771bdb4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('firstname', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('wpi_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=40), nullable=False),
    sa.Column('coursenum', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_coursenum'), ['coursenum'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_major'), ['major'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_year'), ['year'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=40), nullable=False),
    sa.Column('gpa', sa.String(length=5), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=1), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('num_sa', sa.Integer(), nullable=False),
    sa.Column('min_gpa', sa.Integer(), nullable=False),
    sa.Column('min_grade', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_section_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_section_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('past_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('sa_before', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accepted_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_applications')
    op.drop_table('accepted_students')
    op.drop_table('past_enrollments')
    with op.batch_alter_table('course_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_section_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_course_section_course_id'))

    op.drop_table('course_section')
    op.drop_table('teacher')
    op.drop_table('student')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_year'))
        batch_op.drop_index(batch_op.f('ix_course_major'))
        batch_op.drop_index(batch_op.f('ix_course_coursenum'))

    op.drop_table('course')
    op.drop_table('User')
    # ### end Alembic commands ###
